server:
  port: 8081
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckInterval: 15s
        instance-id: provider
        enabled: true
        hostname: localhost
        port: 8081
      enabled: true
  application:
    name: provider